### ISSUE TITLE
Markdown import problem

### ISSUE THREAD

**Issue by nwhitehead** [ulf/markdown2deckjs#7]
Followed instructions, got import error.

./m2d README.md templates/plain.html "Readme"
Traceback (most recent call last):
  File "./m2d", line 9, in <module>
    import mdx_slider
  File "/home/nwhitehead/presentations/markdown2deckjs/mdx_slider.py", line 2, in <module>
    from markdown import etree_loader
ImportError: cannot import name etree_loader

I have Python 2.7.3, markdown module version 2.3.1. I installed dependencies using the recommended pip install command line.

**Comment by jedp** [comment]
@nwhitehead I just ran into the same problem.  PR attached to fix.

**Comment by dsyer** [comment]
Is there a workaround in the meantime before this patch is applied?

**Comment by amberwhitehead** [comment]
@dsyer: You can locally checkout the pull request from @jedp which fixes the problem.  Here's how to do that:

git fetch origin refs/pull/8/head:pr/8
git checkout pr/8
